httpServer:
  name: http-server
  replicaCount: 3
  image: http-server
  port0Name: http
  port0: 8080
  serviceName: http-server-service

configMap:
  name: grpc-configmap
  grpcAddr:
    key: grpc-addr
    value: /logging
  postgresAddr:
    key: postgres-addr
    value: postgres

secret:
  name: postgres-secret
  postgresUser:
    key: postgres-user
    value: cG9zdGdyZXM=
  postgresPassword:
    key: postgres-password
    value: YWRtaW4=
  
loggingServer:
  name: logging-server
  replicaCount: 3
  image: logging
  port0Name: grpc-port-name
  port0: 5051
  serviceName: logging-service

postgres:
  name: postgres
  port: 5432
  image: postgres:latest
  replicaCount: 1
  pvc:
    name: postgres-pvc
  pv:
    name: postgres-pv
    access: ReadWriteOnce
    capacity: 1Gi
    hostPath: /home/mark/postgres
  serviceName: postgres