apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.httpServer.serviceName }}
spec:
  selector:
    app: {{ .Values.httpServer.name }} 
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.httpServer.port0 }}
      targetPort: {{ .Values.httpServer.port0Name }}