apiVersion: v1
kind: Service
metadata:
  name: http-server-service
spec:
  selector:
    app: {{ .Values.httpServer.name }} 
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.httpServer.port0 }}
      targetPort: {{ .Values.httpServer.port0Name }}