apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: central-logging-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "minikube-nginx.hellodevops.net"
    http:
      paths:
      - path: /http
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.httpServer.serviceName }}
            port:
              number: {{ .Values.httpServer.port0 }}
