apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loggingServer.serviceName }}
spec:
  selector:
    app: {{ .Values.loggingServer.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.loggingServer.port0 }}
      targetPort: {{ .Values.loggingServer.port0Name }}
