apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.postgres.pv.name }}
spec:
  capacity:
    storage: {{ .Values.postgres.pv.capacity }}
  accessModes:
    - {{ .Values.postgres.pv.access }}
  hostPath:
    path: {{ .Values.postgres.pv.hostPath }}
