apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgresPvc.name }}
spec:
  accessModes:
    - {{ .Values.postgresPvc.access }}
  resources:
    requests:
      storage: {{ .Values.postgresPvc.storage }}
