apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.pvc.name }}
spec:
  accessModes:
    - {{ .Values.postgres.pv.access }}
  resources:
    requests:
      storage: {{ .Values.postgres.pv.capacity }}
