apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.configMap.postgresAddr.value }}
spec:
  selector:
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}