apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.name }}
type: Opaque
data:
  ## Base64 encoded values
    postgres-user: {{ .Values.secret.postgresUser.value }}
    postgres-password: {{ .Values.secret.postgresPassword.value }}