#https://github.com/paunin/PostDock/blob/master/k8s/example2-single-statefulset/pgpool/pgpool.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-pgpool
  labels:
    name: database-balancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-pgpool
  revisionHistoryLimit: 5
  template:
    metadata:
      name: database-pgpool
      labels:
        name: database-balancer
        app: database-pgpool
    spec:
      containers:
      - name: database-pgpool
        image: postdock/pgpool:latest-pgpool37-postgres11
        livenessProbe:
          exec:
            command: ['bash', '-c', '/usr/local/bin/pgpool/has_write_node.sh && /usr/local/bin/pgpool/has_enough_backends.sh']
          initialDelaySeconds: 600
          timeoutSeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "10m"

        ports:
          - containerPort: 5432
        env:
          # pcp
          - name: "CONFIGS"
            value: "num_init_children:60,max_pool:4,client_idle_limit:900,connection_life_time:300"
          - name: "PCP_USER"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: pcp.user
          - name: "PCP_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: pcp.password

          # Cluster configs  to hearbit checks
          - name: "CHECK_USER"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: replication-user
          - name: "CHECK_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: replication-password
          - name: "DB_USERS"
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: pool.users
          - name: "BACKENDS"
            valueFrom:
              configMapKeyRef:
                name: grpc-configmap
                key: pool.backends
---
apiVersion: v1
kind: Service
metadata:
  name: mysystem-pgpool
  labels:
    name: database-balancer
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: database-balancer