apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  labels:
    app: http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      containers:
      - name: http-server
        image: markbekhet/go-grpc:http-server-1.1
        ports:
        - containerPort: 8080
        env:
        - name: grpcAddr
          valueFrom: 
            configMapKeyRef:
              name: grpc-configmap
              key: grpc-addr
        - name: grpcPort
          valueFrom:
            configMapKeyRef:
              name: grpc-configmap
              key: grpc-port
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-service
spec:
  selector:
    app: http-server 
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080