apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 3 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: postgres-replica
  template:
    metadata:
      labels:
        app: postgres-replica
    spec:
      containers:
        - name: postgres-replica
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: POSTGRES_PRIMARY_HOST
              value: postgres-0.postgres.default.svc.cluster.local
            - name: POSTGRES_PRIMARY_PORT
              value: "5432"
            - name: POSTGRES_REPLICATE_METHOD
              value: basebackup
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
